### ISSUE TITLE
Failed to install plugin from Obsidian store

### ISSUE THREAD

**Issue by meskill** [1C0D/Obsidian-Close-Similar-Tabs#1]
I'm getting error `Failed to install plugin` as obsidian tries to resolve manifest file from the url `https://github.com/1C0D/Obsidian-Close-Similar-Tabs/releases/download/1.2.2/manifest.json` though at release page there some other tag is used

**Comment by 1C0D** [comment]
ok thks for a reason the release tag was unkown. fixed
