### ISSUE TITLE
Feature Request: I don't want to use Tabs!

### ISSUE THREAD

**Issue by 7Codez** [1C0D/Obsidian-Close-Similar-Tabs#10]
How can someone not open Tabs that I do not need?

**Comment by 1C0D** [comment]
be more specific please

**Comment by 7Codez** [comment]
I want only one tab. so that my focus is not distracted.

Could you add an option in your extension settings, to not open any more tabs. I'm sure there are people out there who don't want to use multi-Tabs

I want only one tab.

**Comment by 1C0D** [comment]
do your own plugin. not the same here, this is to close  duplicates tabs. so by definition using several tabs.
