### ISSUE TITLE
[Bug] Plugins breaks Obsidian startup

### ISSUE THREAD

**Issue by meskill** [1C0D/Obsidian-Close-Similar-Tabs#11]
Starting with version 1.50.0 of the plugin when it is enabled my Obsidian doesn't start at all as it get stuck on "loading workspaces"

**Comment by 1C0D** [comment]
Could you please delete the plugin. the folder .obsidian/plugins/close-similar-tabs and tell me if it is the same with version 1.5.1, if so I will undo what I did.

**Comment by 1C0D** [comment]
ok I found why it's happening. it's happening when restarting obsidian with a pinned tab. I've already saw this on another plugin.

**Comment by meskill** [comment]
With 1.5.1 there is no issue indeed, thanks.

**Comment by meskill** [comment]
though, I'm still facing other issues after update. The main window for [plugin update tracker](https://github.com/swar8080/obsidian-plugin-update-tracker) is not opening when "Close Similar tabs" is active. It wasn't the problem before
