### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Duncma** [1C0D/Obsidian-Close-Similar-Tabs#15]
The plugin hasn't worked for some time. I usually have 3 windows open in Obsidian and I have all the Close Similar Tabs options switched on and All Windows selected from the dropdown.

I'm running Obsidian version 1.4.16 with the Obuntu theme.

I've tried uninstalling and re-installing the plugin, as well as changing to the default theme, but it makes no difference.

Any ideas on what else to try?

**Comment by 1C0D** [comment]
Totally new version. I was stuck with something else, sry
