### ISSUE TITLE
A bug when I try to open a page in a new tab

### ISSUE THREAD

**Issue by dutry** [1C0D/Obsidian-Close-Similar-Tabs#19]
Dear developer,

I am a Mac user, and I have also tested this on a Windows PC (use Ctrl instead of Command), and the bug persists.

I want to report that this plugin used to work perfectly fine for me.

However, after upgrading it to the latest version, I've encountered an issue. When I use Command+O to open new pages, then after I have selected the page I want to go, and press Command+Enter simultaneously to open them in a new tab, if I'm opening a previously existing page, it takes me back to that previously existing page and changes the page I came from to the homepage.

But I don't want it change the page I came from to the homepage! Please feel free to check it yourself

**Comment by 1C0D** [comment]
fixed
