### ISSUE TITLE
still having pinned tab issue after 2.1.3

### ISSUE THREAD

**Issue by pcause** [1C0D/Obsidian-Close-Similar-Tabs#20]
i Have one pinned tab open.  I open my daily note and get that tab but also an empty tab.  I have the following in my template for the daily note:

> `$= let x=app.workspace.activeLeaf.setPinned(1); ""`

which makes the note pin.

**Comment by 1C0D** [comment]
I'm not familiar with this.
 you use a daily using a template, with what templater ? please give me the exact snippet to do it. I tried but this not working.

**Comment by 1C0D** [comment]
fixed
