### ISSUE TITLE
bug report: when use superlink in the page, will close this page

### ISSUE THREAD

**Issue by dutry** [1C0D/Obsidian-Close-Similar-Tabs#21]
I am using macos version of Obsidian.

When I click a superlink inside this page (goes to a title in side the same page), this plugin will close this tab.

For example, when I click [# title 1], and # title 1 is a title inside the page, then the plugin will close this page.

**Comment by 1C0D** [comment]
I checked it. I don't have this issue. it was on the most recent version
? 2.1.12
Now I just added a command and it's 2.2.1

**Comment by dutry** [comment]
I am using the latest version of 2.2.1. And I can still reproduce the bug.

You might copy the text below to reproduce the bug:

```md
[[#this is the title]]

# this is the title 
```

And then when you click the link of first line, it will close the page.

**Comment by 1C0D** [comment]
ah I always used the name file before the  # and that's not doing it...
ok fixed.
thks for the report and your precision

**Comment by dutry** [comment]
very efficient of you
