### ISSUE TITLE
Opening a file with middle mouse

### ISSUE THREAD

**Issue by RealRavens** [1C0D/Obsidian-Close-Similar-Tabs#22]
Unlike clicking a file or ctrl clicking a file to open seperate tab; opening a file in a seperate tab with middle mouse button doesn't seem to count or activate the plugin. Can open many of the same file.

**Comment by 1C0D** [comment]
I even didn't know it was possible. but thks for the trick it can be useful on laptop.
Fixed on version 2.3.1
