### ISSUE TITLE
Bug: Incompatible with the 'Hover Editor' plugin in 2.3.1

### ISSUE THREAD

**Issue by alexinea** [1C0D/Obsidian-Close-Similar-Tabs#23]
In version 2.3.1, there is again [an incompatibility issue with the Hover Editor](https://github.com/1C0D/Obsidian-Close-Similar-Tabs/issues/16). When this plugin is enabled and the note is previewed using the Hover Editor, the preview box displays the default page instead of the content of the note.

![image](https://github.com/1C0D/Obsidian-Close-Similar-Tabs/assets/980129/6cf19296-7a27-4939-bbaf-03fcf411ef9a)
When `obsidian-close-similar-tabs` is enabled.

![image](https://github.com/1C0D/Obsidian-Close-Similar-Tabs/assets/980129/c24a8f0a-c81b-4f3d-8f21-6fa37325c840)
When `obsidian-close-similar-tabs` is disabled.

**Comment by 1C0D** [comment]
Ok done v2.3.2

**Comment by 1C0D** [comment]
Ok done. version 2.3.2
