### ISSUE TITLE
Plugin does not start on mobile

### ISSUE THREAD

**Issue by Adriz1er** [1C0D/Obsidian-Close-Similar-Tabs#24]
Failed to load

**Comment by dutry** [comment]
The same problem, cannot work on ipad and android devices.

The plugin used to be good on mobile devices

**Comment by 1C0D** [comment]
v2.3.4 back to version 2.3.1 (fix on hover editor). Is this version ok? 

I was changing the way I'm handling plugins. Apparently I used something too recent.

**Comment by 1C0D** [comment]
v2.3.8
should be fixed now
thks to confirm. I don't have a mobile to test it

**Comment by 1C0D** [comment]
Ok Done
