### ISSUE TITLE
The hover editor opens frequently as a new TAB

### ISSUE THREAD

**Issue by jiajiala** [1C0D/Obsidian-Close-Similar-Tabs#25]
I don't know what's happening, but when I use this plugin, another plugin, hover editor, doesn't open files in the hover window, often showing up as new tabs

**Comment by 1C0D** [comment]
It has been fixed 3 versions ago. I checked it's working version 2.3.6
if you have still a problem, describe exactly what you are doing.

**Comment by RealRavens** [comment]
Ya hover editor still not functioning. Here's an example of hovering over in files area over a note. Note: Home tab is my default for a blank new tab, but same behaviour as @jiajiala was mentioning.

[![Image from Gyazo](https://i.gyazo.com/ea965ac3b0fad6ce7db33c3db0a19427.gif)](https://gyazo.com/ea965ac3b0fad6ce7db33c3db0a19427)

It's hard to say why it's happening. I guess I'll have to check the backend of both plugins. But possibly is hover editor hiding a tab while it makes a window? Not sure. Could be a bunch of things, but I'd be guessing.

**Comment by 1C0D** [comment]
version 2.3.6 I suppose you are showing the popout not closing? I don't have this behaviour. It's closing directly

**Comment by 1C0D** [comment]
oh I see now your tab is pinned.

**Comment by 1C0D** [comment]
I tried on a pinned hover window too. that's not closing. 
Maybe I missed some options? I tried to change almost all. I can't still not reproduce.

**Comment by RealRavens** [comment]
So I've done some testing. I disabled all plugins except hover and similar tabs. I've found the problem to be which setting you have "Default Mode" in. If you're in "reading mode" which I believe is the original default, it works properly with your plugin. If you have the setting in "editing mode" then it no longer functions.

[![Image from Gyazo](https://i.gyazo.com/cb3275e8cae95d6eafaade5cb7a4b49c.png)](https://gyazo.com/cb3275e8cae95d6eafaade5cb7a4b49c)

Here's a demonstration of me switching between the two.

[![Image from Gyazo](https://i.gyazo.com/54fda86b9ff37ad817ed00a838a3330c.gif)](https://gyazo.com/54fda86b9ff37ad817ed00a838a3330c)

**Comment by 1C0D** [comment]
ok done

**Comment by RealRavens** [comment]
> ok done

Great work @1C0D! Appreciate the dedication to your plugin. 👍
Works like a charm.

**Comment by 1C0D** [comment]
Indeed, I spend a lot of time on this one. I had to have a military organization to debug each situation. In reality, they are many possible scenarios...
