### ISSUE TITLE
Feature Request: Support for both dataview and dataviewjs paragraph links?

### ISSUE THREAD

**Issue by loewenherzt** [1C0D/Obsidian-Close-Similar-Tabs#26]
The plugin works for links in dataview task blocks, but not in dataviewjs blocks such as:

```dataviewjs
dv.paragraph('```task\n' + 'tags includes todo' + '\n```')
```

**Comment by 1C0D** [comment]
technically, I have absolutely 0 knowledge about dataviewjs
and I don't see any link in your example, I guess it's in the result table
so what I need? a page with a tag todo? and then ? Explain me in detail please so I can reproduce it to see how CST behaves in this situation and I can help to fix this.

**Comment by 1C0D** [comment]
Version 3.1.2
ok thks for the fine explanations. it should be ok now

**Comment by loewenherzt** [comment]
> Version 3.1.2 ok thks for the fine explanations. it should be ok now

That was quick! Thanks a lot. I can verify that the plugin works with links from the Dataview block!
However in links from the dataviewjs block it didn't (using the same test as the previous post)

**Comment by 1C0D** [comment]
lol I was at the library and it was closing. I forgot this part of your message. thanks to remind me. I will try this now.

**Comment by 1C0D** [comment]
well the first one was using open link the second one open file. it should be quick

**Comment by 1C0D** [comment]
version 5.2.5
ok done for dataviewjs this time.
I'm super bad with those plugins...

**Comment by loewenherzt** [comment]
it works! thanks
