### ISSUE TITLE
Plugin preventing the opening of notes in a new tab when using Omnisearch plugin

### ISSUE THREAD

**Issue by sidahmed-malaoui** [1C0D/Obsidian-Close-Similar-Tabs#28]
This obsidian plugin is preventing the opening of notes in a new tab when we do the search using Omnisearch plugin. 

For example, when searching for a note (using Omnisearch), and click ctrl+enter , the note is always opened in the same tab. I tried disabling this plugin, and the open in new tab functionality works fine.

**Comment by 1C0D** [comment]
version 3.1.1
ok fixed

**Comment by sidahmed-malaoui** [comment]
I can confirm, it's fixed.

Thank you for your reactivity and for this amazing plugin.
