### ISSUE TITLE
The plugin breaks core Obsidian internal linking functionality

### ISSUE THREAD

**Issue by lunule** [1C0D/Obsidian-Close-Similar-Tabs#33]
Hi,

The plugin breaks the core/default Obsidian internal linking functionality - meaning, when internal linking is used in a file, and such link is clicked, the plugin interprets this click as an attempt of opening an already open file, thus, instead of scrolling to the target (header, block, etc.), it closes the file.

Otherwise, this is an awesome plugin, fixing a significant issue with how Obsidian tabbing works - but it would be great if this bug could be fixed somehow (e.g. exclude clicks on internal links including the `^` character).

**Comment by 1C0D** [comment]
you mean a wikilink as [[page1]] and a single click on it ? I don't have this issue ? on what platform are you ?

**Comment by lunule** [comment]
@1C0D Yup, a wikilink, but with a header or a block identifier, used in the same file. 

Example: a '[[page1#header-1]]' link, used in the same 'page1' file.

The expected behaviour when such link is clicked is a scroll to the target - but the plugin interprets it as an open event upon an already-opened note, thus it closes the file. 

I'll do some additional testing this evening with a test vault to check what happens when other plugins are disabled.

Platform is Windows 11.

**Comment by lunule** [comment]
OK, I tested the issue with a new empty vault - the only community plugin installed is the Close Similar Tabs plugin.
The issue persists in the test environment as well.

![tab-closing-on-inner-link-click](https://github.com/1C0D/Obsidian-Close-Similar-Tabs/assets/190486/a61936ae-4ace-404e-b5e6-07e2dccf745d)

**Comment by mariomui** [comment]
YUp this is broken for me as well. I didnt have this problem until very recently.

**Comment by 1C0D** [comment]
Version 3.1.6
ok fixed

**Comment by lunule** [comment]
Thanks @1C0D for the quick fix. 🙏
