### ISSUE TITLE
Option to only close similar tabs in the same tab group/panel

### ISSUE THREAD

**Issue by distbit0** [1C0D/Obsidian-Close-Similar-Tabs#5]
Hi this extension is super useful but it prevents the split down/split right commands from working, as a result of the fact that they duplicate the current tab in a new panel. Could you pls add an option to only close similar tabs which are in the same tab group, so as to not interfere with the functioning of split down/split right? many thx

**Comment by 1C0D** [comment]
Thanks for letting me know this. It's now supporting split panels
