### ISSUE TITLE
Feature Request: When clicking on a link to an already open tab, return to the previous page, switch to the tab with the already open note, and show a notification instead.

### ISSUE THREAD

**Issue by YousufSSyed** [1C0D/Obsidian-Close-Similar-Tabs#6]
Let's say I have a link in page 1 that goes to page 2 but its already opened. As of now, the plugin will just close the tab that was just on page 1, right after clicking it. It should do the following instead:

* After clicking the link, return to page 1.
* Switch to the tab that has page 2 open.
* Show a notification saying "Page 2 is already open."

You could also make this an opt-out setting in the settings menu.

**Comment by 1C0D** [comment]
what version have you? it's not doing this. it's going to the page 2 that you want to open even if already opened. I added notifications in option.

**Comment by 1C0D** [comment]
what version have you? it's not doing this. it's going to the page 2 that you want to open even if already opened. I added notifications in option.

**Comment by 1C0D** [comment]
I think I didn't understand what you wanted untill recently. I always use ctrl and click opening a link from a page, to keep the previous page opened and keep the previous opened duplicate tab with it's history. but I changed the behaviour when just clicking on a link now. It will keep the last opened tab and an history of navigation so you can get back to previous page. the previous opened duplicated tab is closed. this is the way obsidian usually works when opening a link from a page. but I did a bug report (even it's not really a bug) to ask to copy the history if a similar tab was already opened with some edit history. Of course there obsidian doesn't close the duplicate. but it could happen manually and you are maybe loosing the edit history, whithout really knowing it... 
I think this is what you meant, to have a more usual behavior. isn't it?
I'm french by the way, so I understand with my level of english...

**Comment by YousufSSyed** [comment]
@1C0D Your English is fine, though its much harder to read long paragraphs since they're walls of text, I recommend breaking them up into smaller paragraphs.

About the request, its an interesting feature you added, to close the other tab instead. Perhaps some users would want this, and I'd recommend making a setting: If you open a link in a tab to a note that's already opened, choose between closing the tab you clicks the link on, or the other one(s).

Going back to my original request, what I meant was that if you open a link on a note to a tab that's already opened, it should return to the page you clicked the link on, switch to the note whose link you click on, and make a notification saying the plugin did just that.
