### ISSUE TITLE
Feature Request: Show notifications when duplicate tabs are closed.

### ISSUE THREAD

**Issue by YousufSSyed** [1C0D/Obsidian-Close-Similar-Tabs#7]
When duplicate tabs are closed, show a notification saying "duplicate tabs for [page name] have been closed. Page was accessed by _." as well as how the user opened the duplicate page. This could be an opt-in or opt-out setting in the settings menu. Also refer to my other PR with something similar (but not the same thing): https://github.com/1C0D/Obsidian-Close-Similar-Tabs/issues/6.

**Comment by 1C0D** [comment]
I will consider this.

**Comment by 1C0D** [comment]
ok, I added an option to have a notification when the file was already opened. btw it's AFAIK it's not possible to know how the file was opened. and it will be to many info to read...
