### ISSUE TITLE
Feature Request: Is it possible to toggle whether duplicates when links are opened in certain ways?

### ISSUE THREAD

**Issue by YousufSSyed** [1C0D/Obsidian-Close-Similar-Tabs#8]
There are some different ways of opening notes:
* File Explorer
* Search Menu
* Commands
* Obsidian URIs: https://help.obsidian.md/Advanced+topics/Using+Obsidian+URI
* Links
* And more I'm probably not thinking of?

Is it it possible to see the way a link is opened in the Obsidian API? If so, perhaps you could enable / disable closing tabs that are opened in certain ways like I described above.

**Comment by 1C0D** [comment]
AFAIK there is no way to know how a file was opened. The only thing I could do was to know if the click was in the explorer to not allow close similar tabs in this condition. So I added this option. Not super useful after a lot of tries to do it, but why not.
