### ISSUE TITLE
Feature request: Add a command to reopen the last closed duplicate tab.

### ISSUE THREAD

**Issue by YousufSSyed** [1C0D/Obsidian-Close-Similar-Tabs#9]
What if I want the tabs to be de-duplicated most of the time, but not all the time? A command like this would come in handy.

**Comment by 1C0D** [comment]
There is a command to access quickly settings and then disable duplicate tabs, "close similar tabs".

**Comment by YousufSSyed** [comment]
Well, maybe I want to open a duplicate real quick to look at it, and quickly navigate back and forth between the tab and the one next to it. I have hotkeys for the commands "Previous Tab" and "Next Tab". The other tab for the page could be far away. Another thing, I might have a note open scrolled to one area of the page, and I may want another tab open at another section of it.

**Comment by YousufSSyed** [comment]
Another thing, I've noticed that I open already opened links on accident and lose the tab I was just working on.

**Comment by YousufSSyed** [comment]
@1C0D This doesn't look like it was completed.

**Comment by 1C0D** [comment]
@YousufSSyed I discovered that another plugin I did 'open file in explorer' was masking the fact that the opened file was not automatically deleted. With this plugin enabled, it was working well. Or same when having the option "always focus new tabs" enabled. I found this doing a new vault, so I will do a quick fix for this. I couldn't see bugs you described before to find this. The most pernicious bug I ever had.

**Comment by 1C0D** [comment]
Not in the same window? Between several windows, that's intentional. It has to be reopened or chose the option current window only. I found a major default BTW that I couldn't see using another plugin that I did "reveal in explorer" or using the option "always focus new tabs". It was not deleting duplicate without clicking on it. Now in most cases that's did automatically. After I will my limits, I think.

**Comment by YousufSSyed** [comment]
I only have one window open, when a tab gets closed I can't undo that tab getting closed.

**Comment by 1C0D** [comment]
"Another thing, I've noticed that I open already opened links on accident and lose the tab I was just working on." you can navigate back now with the new version, which is a total refactoring

**Comment by 1C0D** [comment]
"What if I want the tabs to be de-duplicated most of the time, but not all the time? A command like this would come in handy." you can now pin a tab it will be ignored, and you can duplicate it (once)

**Comment by YousufSSyed** [comment]
I'd still want a command though in case I open duplicates on accident. Can you reopen the issue?

**Comment by 1C0D** [comment]
there is a command in obsidian for this

**Comment by YousufSSyed** [comment]
But then its gets closed as a duplicate again, the plugin should either not close it again when the command is run, or if it can't then it should provide its own command to not close the duplicate.

**Comment by YousufSSyed** [comment]
@1C0D Did you get my last reply?

**Comment by 1C0D** [comment]
do a video about what you mean, or try to be more specific. I really don't get your point. I tried hard, but I don't understand what you mean.

**Comment by YousufSSyed** [comment]
> there is a command in obsidian for this. undo close tab.

I meant that if you use this command to open a tab that was closed by the plugin, the plugin will immediately close it again. So I asked if you either stop that, or provide a command in the plugin to undo closing the tab without immediately closing it again.

Is that more clear?

**Comment by 1C0D** [comment]
it should be ok now.

**Comment by YousufSSyed** [comment]
@1C0D What do you mean, can you elaborate?

**Comment by YousufSSyed** [comment]
@1C0D I update the plugin to 1.7.3 and I still have the issue.

**Comment by YousufSSyed** [comment]
@1C0D Have u looked at this lately?
